# Generated by Django 4.2.18 on 2025-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_alter_manifestation_description_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manifestations',
            field=models.ManyToManyField(related_name='users', to='manifest.manifestation'),
        ),
    ]
