# Generated by Django 4.2.18 on 2025-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='style_choice',
            field=models.CharField(choices=[('moon', 'Moon'), ('neutral', 'Neutral'), ('nature', 'Nature'), ('sun', 'Sun'), ('stars', 'Stars'), ('cosmic', 'Cosmic'), ('witchy', 'Witchy'), ('hearts', 'Hearts'), ('antique', 'Antique'), ('pastel', 'Pastel')], max_length=10),
        ),
    ]
