# Generated by Django 4.2.18 on 2025-01-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_alter_manifestation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestation',
            name='owner',
        ),
    ]
