# Generated by Django 4.2.18 on 2025-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_remove_manifestation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='can_charge',
            field=models.BooleanField(default=True),
        ),
    ]
